# Generated by Django 4.2.7 on 2024-01-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0002_uesrbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='drug_img',
            field=models.ImageField(null=True, upload_to='templates/images'),
        ),
    ]
