# Generated by Django 4.2.7 on 2024-01-04 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0008_alter_drug_drug_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('drug_name', models.CharField(max_length=255)),
                ('drug_qty', models.IntegerField()),
                ('drug_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.d_type')),
            ],
        ),
    ]
