# Generated by Django 4.2.7 on 2024-01-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0009_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='uesrbuy',
            new_name='userbuy',
        ),
    ]
