# Generated by Django 4.2.7 on 2024-01-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0010_rename_uesrbuy_userbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('tal', models.CharField(max_length=255)),
                ('drug_name', models.CharField(max_length=255)),
                ('drug_qty', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='report',
        ),
    ]
