# Generated by Django 4.2.7 on 2024-01-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0013_remove_product_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_buy',
            name='id',
        ),
        migrations.AddField(
            model_name='report_buy',
            name='report_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
