# Generated by Django 4.2.7 on 2024-01-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_app', '0014_remove_report_buy_id_report_buy_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_buy',
            name='report_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
